import "./globals.css";
import "next-cloudinary/dist/cld-video-player.css";
import { ClerkProvider } from "@clerk/nextjs";
import MainRootLayout from "@/components/layouts/MainRootLayout";

export const metadata = {
  title: "Talanta Mines - Talent Marketplace",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`antialiased`}>
          <MainRootLayout>{children}</MainRootLayout>
        </body>
      </html>
    </ClerkProvider>
  );
}
